### ISSUE TITLE
Add tag system 

### ISSUE THREAD

**Issue by clement-amat** [gregoryalary/laranotes#3]
A note might be associated to 0, or several tags.
Add an option to list note by tags.

Example : **laranotes** **tag** _work personnal_

**Comment by gregoryalary** [comment]
Done.
Syntax : 
- Create -> `laranotes create --tag=mytag Content of the note`, the tag is optional.
- All -> `laranotes all --tag=mytag1 --tag=mytag2', the tags also are optional.
